#!/bin/bash
# Commands to test Takakrypt full functionality
# Run each command manually with sudo

echo "===== Takakrypt Full Test Commands ====="
echo ""
echo "1. First, build the components:"
echo "   make go-build"
echo "   cd kernel && make && cd .."
echo ""
echo "2. Load kernel modules:"
echo "   sudo insmod kernel/takakrypt.ko debug_level=2"
echo "   sudo insmod kernel/takakryptfs/takakryptfs.ko"
echo ""
echo "3. Check modules loaded:"
echo "   lsmod | grep takakrypt"
echo "   cat /proc/takakrypt/status"
echo ""
echo "4. Start the agent:"
echo "   sudo ./build/bin/takakrypt-agent -config configs/test-config.yaml &"
echo ""
echo "5. Create test directories:"
echo "   sudo mkdir -p /tmp/takakrypt-lower /tmp/takakrypt-mount"
echo ""
echo "6. Mount takakryptfs:"
echo "   sudo mount -t takakryptfs /tmp/takakrypt-lower /tmp/takakrypt-mount -o policy=test_policy"
echo ""
echo "7. Create test files:"
echo "   echo 'Secret data' | sudo tee /tmp/takakrypt-mount/secret.txt"
echo "   echo 'Test document' | sudo tee /tmp/takakrypt-mount/test.doc"
echo "   echo 'Debug log' | sudo tee /tmp/takakrypt-mount/debug.log"
echo ""
echo "8. Check encryption (lower directory):"
echo "   sudo hexdump -C /tmp/takakrypt-lower/secret.txt | head -5"
echo "   sudo hexdump -C /tmp/takakrypt-lower/test.doc | head -5"
echo "   sudo hexdump -C /tmp/takakrypt-lower/debug.log | head -5"
echo ""
echo "9. Read through mount (should see plaintext):"
echo "   sudo cat /tmp/takakrypt-mount/secret.txt"
echo "   sudo cat /tmp/takakrypt-mount/test.doc"
echo ""
echo "10. Test as different users:"
echo "    sudo -u testuser1 cat /tmp/takakrypt-mount/secret.txt"
echo "    sudo -u nobody cat /tmp/takakrypt-mount/secret.txt"
echo ""
echo "11. Check system status:"
echo "    cat /proc/takakrypt/status"
echo "    cat /proc/takakrypt/cache"
echo ""
echo "12. Cleanup:"
echo "    sudo umount /tmp/takakrypt-mount"
echo "    sudo pkill takakrypt-agent"
echo "    sudo rmmod takakryptfs"
echo "    sudo rmmod takakrypt"
echo ""
echo "===== End of Commands ====="