# Takakrypt Test Configuration for Linux VM
# Users: testuser1, testuser2, ntoi

guard_points:
  - name: "sensitive_documents"
    path: "/tmp/secure"
    recursive: true
    policy: "admin_only"
    include_patterns:
      - "*.txt"
      - "*.doc"
      - "*.pdf"
    enabled: true

  - name: "shared_files"
    path: "/tmp/shared"
    recursive: true
    policy: "test_users_policy"
    enabled: true

  - name: "ntoi_private"
    path: "/tmp/ntoi-private"
    recursive: true
    policy: "ntoi_only"
    enabled: true

policies:
  admin_only:
    algorithm: "AES-256-GCM"
    key_size: 256
    user_sets: ["admin_users"]
    audit_level: "info"
    enabled: true

  test_users_policy:
    algorithm: "AES-256-GCM"
    key_size: 256
    user_sets: ["test_users", "admin_users"]
    require_all_sets: false
    audit_level: "debug"
    enabled: true

  ntoi_only:
    algorithm: "ChaCha20-Poly1305"
    key_size: 256
    user_sets: ["admin_users"]
    audit_level: "info"
    enabled: true

user_sets:
  test_users:
    name: "Test Users Group"
    users: ["testuser1", "testuser2"]
    description: "Standard test users"

  admin_users:
    name: "Admin Users Group"
    users: ["ntoi"]
    description: "Administrative users with full access"

  all_users:
    name: "All System Users"
    users: ["testuser1", "testuser2", "ntoi"]
    description: "All test users combined"

process_sets:
  trusted_editors:
    name: "Trusted Text Editors"
    processes: ["vim", "nano", "gedit", "cat", "less"]
    description: "Safe text editing processes"

  system_tools:
    name: "System Tools"
    processes: ["cp", "mv", "ls", "find"]
    description: "Basic system utilities"

resource_sets:
  documents:
    name: "Document Files"
    file_patterns: [".*\\.(txt|doc|pdf|md)$"]
    extensions: [".txt", ".doc", ".pdf", ".md"]
    description: "Text and document files"

  sensitive_data:
    name: "Sensitive Files"
    file_patterns: [".*secret.*", ".*confidential.*", ".*private.*"]
    description: "Files with sensitive keywords"

kms:
  endpoint: "mock://localhost"
  auth_method: "token"
  timeout: "10s"
  retry_attempts: 3
  key_cache_ttl: "1h"
  policy_cache_ttl: "15m"

agent:
  log_level: "debug"
  log_path: "/tmp/takakrypt-agent.log"
  audit_log_path: "/tmp/takakrypt-audit.log"
  socket_path: "/tmp/takakrypt-agent.sock"
  worker_threads: 4
  max_cache_size: 1000
  cache_cleanup_interval: "5m"
  request_timeout: "30s"
  enable_metrics: true
  metrics_port: 9090