# Test configuration for ordered security rule evaluation
# Based on Thales CTE analysis

guard_points:
  - name: "mysql_database"
    path: "/var/lib/mysql/production"
    recursive: true
    policy: "mysql_protection"
    enabled: true

  - name: "user_documents"
    path: "/home/*/Documents"
    recursive: true
    policy: "document_protection"
    enabled: true

# Resource sets (what to protect)
resource_sets:
  mysql_data:
    description: "MySQL database files"
    file_patterns:
      - "*.frm"
      - "*.ibd"
      - "*.MYD"
      - "*.MYI"
    directories:
      - "/var/lib/mysql/production"

  sensitive_docs:
    description: "Sensitive document files"
    file_patterns:
      - "*.doc"
      - "*.docx"
      - "*.pdf"
      - "*.txt"
    extensions:
      - ".confidential"

  log_files:
    description: "Log files (usually excluded)"
    file_patterns:
      - "*.log"
      - "*.tmp"

# User sets (who can access)
user_sets:
  mysql_users:
    description: "MySQL database users"
    users:
      - "mysql"
      - "mariadb"
    uids:
      - 116  # mysql UID

  db_admins:
    description: "Database administrators"
    users:
      - "dba"
      - "root"
    groups:
      - "wheel"
      - "sudo"

  document_users:
    description: "Document access users"
    users:
      - "ntoi"
      - "testuser1"
      - "testuser2"
    uids:
      - 1000
      - 1001
      - 1002

  denied_users:
    description: "Explicitly denied users"
    users:
      - "nobody"
    uids:
      - 99999

# Process sets (which applications)
process_sets:
  mysql_processes:
    description: "MySQL database processes"
    processes:
      - "mysqld"
      - "mariadbd"
    process_paths:
      - "/usr/sbin/mysqld"
      - "/usr/sbin/mariadbd"

  admin_tools:
    description: "Administrative tools"
    processes:
      - "bash"
      - "vim"
      - "nano"
    process_paths:
      - "/bin/bash"
      - "/usr/bin/vim"
      - "/usr/bin/nano"

  text_editors:
    description: "Text editing applications"
    processes:
      - "cat"
      - "less"
      - "head"
      - "tail"

# Policies with ordered security rules
policies_v2:
  mysql_protection:
    name: "mysql_protection"
    type: "live_data_transformation"
    algorithm: "AES-256-GCM"
    key_size: 256
    version: 1
    key_version: 1
    enabled: true
    security_rules:
      # Rule 1: Key operations (highest priority)
      - order: 1
        resource_set: ""           # All resources
        user_set: ""               # All users
        process_set: ""            # All processes
        actions: ["key_op"]
        effects: ["permit", "applykey"]
        browsing: false
        description: "Allow key operations for all users"

      # Rule 2: MySQL database access
      - order: 2
        resource_set: "mysql_data"
        user_set: "mysql_users"
        process_set: "mysql_processes"
        actions: ["f_rd", "f_wr", "f_cre", "f_rm", "d_rd"]
        effects: ["permit", "audit", "applykey"]
        browsing: true
        description: "MySQL processes can access database files with encryption"

      # Rule 3: DBA administrative access
      - order: 3
        resource_set: "mysql_data"
        user_set: "db_admins"
        process_set: "admin_tools"
        actions: ["read", "d_rd"]
        effects: ["permit", "audit"]
        browsing: true
        description: "Database admins can read encrypted files (no write)"

      # Rule 4: Deny explicitly denied users
      - order: 4
        resource_set: ""
        user_set: "denied_users"
        process_set: ""
        actions: ["all_ops"]
        effects: ["deny", "audit"]
        browsing: false
        description: "Deny access to blocked users"

      # Rule 5: Default deny all others
      - order: 5
        resource_set: ""
        user_set: ""
        process_set: ""
        actions: ["all_ops"]
        effects: ["deny", "audit"]
        browsing: false
        description: "Default deny for unmatched access"

  document_protection:
    name: "document_protection"
    type: "live_data_transformation"
    algorithm: "AES-256-GCM"
    key_size: 256
    version: 1
    key_version: 1
    enabled: true
    security_rules:
      # Rule 1: Allow log files without encryption
      - order: 1
        resource_set: "log_files"
        user_set: ""
        process_set: ""
        actions: ["all_ops"]
        effects: ["permit"]
        browsing: true
        description: "Allow log files without encryption"

      # Rule 2: Document users can access sensitive documents
      - order: 2
        resource_set: "sensitive_docs"
        user_set: "document_users"
        process_set: "text_editors"
        actions: ["read", "write", "f_rd", "f_wr", "f_cre"]
        effects: ["permit", "audit", "applykey"]
        browsing: true
        description: "Authorized users can access documents with encryption"

      # Rule 3: Default deny
      - order: 3
        resource_set: ""
        user_set: ""
        process_set: ""
        actions: ["all_ops"]
        effects: ["deny", "audit"]
        browsing: false
        description: "Default deny for document access"

# KMS configuration
kms:
  endpoint: "http://localhost:8080"
  auth_method: "token"
  timeout: "30s"
  retry_attempts: 3
  key_cache_ttl: "1h"
  policy_cache_ttl: "30m"

# Agent configuration
agent:
  socket_path: "/var/run/takakrypt.sock"
  log_level: "debug"
  log_path: "/var/log/takakrypt.log"
  audit_log_path: "/var/log/takakrypt-audit.log"
  max_cache_size: 1000
  worker_threads: 4
  request_timeout: "30s"
  enable_metrics: true
  metrics_port: 9090