guard_points:
  - name: "test_documents"
    path: "/tmp"
    recursive: true
    policy: "test_policy"
    enabled: true

policies:
  test_policy:
    algorithm: "AES-256-GCM"
    key_size: 256
    audit_level: "debug"
    enabled: true

user_sets:
  test_users:
    users: ["testuser"]

kms:
  endpoint: "mock://localhost"
  auth_method: "token"
  timeout: "10s"

agent:
  log_level: "debug"
  worker_threads: 2
  socket_path: "/tmp/takakrypt-test.sock"